apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-master
        image: kubernetes/redis:latest
        env:
          - name: MASTER
            value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.01"
            memory: 64Mi
